#ifndef _DEFINE_H_
    #define _DEFINE_H_
#define PI 3.14159265358979323846
#define CIRCULO "circulo"
#define ARRIBA "arriba"
#define	ABAJO "abajo"
#define	IZQUIERDA "derecha"
#define	DERECHA "izquierda"
#define RESOLUCION_640 640
#define RESOLUCION_640_ALTO 480
#define RESOLUCION_640_ANCHO 640
#define RESOLUCION_800 800
#define RESOLUCION_800_ALTO 600
#define RESOLUCION_800_ANCHO 800
#define RESOLUCION_1024 1024
#define RESOLUCION_1024_ALTO 768
#define RESOLUCION_1024_ANCHO 1024
#define RESOLUCION_1280 1280
#define RESOLUCION_1280_ALTO 768
#define RESOLUCION_1280_ANCHO 1280
#define POS_PAD1_Y_PORCENTAJE  0.88
#define POS_PAD2_Y_PORCENTAJE  0.08
#define RADIO__TEJO "radioTejo"
#define BASE__PAD "basePad"
#define ALTURA__PAD "alturaPad"
#define VELOCIDAD__TEJO  "velocidadTejo"
#define VELOCIDAD__PAD  "velocidadPad"
#define IDTEXTURA__TEJO "idTexturaTejo"
#define IDTEXTURA__PAD "idTexturaPad"
#define BASE_ARCO 10

#define ID "id"
#define RADIO "radio"
#define LADO "lado"
#define BASE "base"
#define ALTURA "altura"
#define VELOCIDAD "velocidad"
#define PATH "path"
#define TEXTURA "textura"
#define CUADRADO "cuadrado"
#define RECTANGULO "rectangulo"
#define TRIANGULO "triangulo"
#define TEJO "tejo"
#define PAD "pad"
#define CIRCULO "circulo"
#define DELIMITADOR "\""
#define GENERAL "General"
#define TEXTURA_FIG "texturaFig"
#define TEXTURA_ESC "texturaEsc"
#define RESOLUCION "resolucion"
#define COLOR_FONDO_FIG "colorFondoFig"
#define COLOR_FONDO_ESC "colorFondoEsc"
#define COLOR_LINEA "colorLinea"
#define POS_X "x"
#define POS_Y "y"
#define POSICION_X 'x'
#define POSICION_Y 'y'
#define POS_X1 "x1"
#define POS_Y1 "y1"
#define POS_X2 "x2"
#define POS_Y2 "y2"
#define POS_X3 "x3"
#define POS_Y3 "y3"
#define SEGMENTO "segmento"
#define COLOR_FIGURA "colorFigura"
#define ID_TEXTURA "idTextura"
#define X1 "x1"
#define X2  "x2"
#define Y1 "y1"
#define Y2 "y2"
#define SINVALOR "sinValor"
#define POS_TEJO_X_INICIAL  150
#define POS_TEJO_Y_INICIAL  300
#define POS_PAD1_X_INICIAL  710
#define POS_PAD1_Y_INICIAL  240
#define POS_PAD2_X_INICIAL  56
#define POS_PAD2_Y_INICIAL  240
#define PORCENTAJE_ARCO 0.5
#define  PIXELES_SALTO 2
#define  PIXELES_SALTO_TEJO 3
#define  NUM_TECLAS 9
#define MARCADOR_TAG  '-'
#define PUNTAJE_GOL 10
//tamanio de letra de los puntajes
#define TAMANIO_LETRA 60
#define ANCHO_PUNTAJES 100
#define ALTO_PUNTAJES 100
#endif
