ar#ifndef __DEFINE_H__
#define __DEFINE_H__


#define NOT_CONNECTED 0
#define ACTIVADO 0
#define CONNECTED 1
#define NO_HOST 2
#define DEBUG 0
#define VELOCIDAD_DE_FRAMES_POR_SEGUNDO 10
#define PI 3.141592653
#define PI 3.141592653
#define NUMERO_PEQUENIO 0.0000001
#define SIN_VALOR "sinValor"
#define PAD_DERECHA "padDerecha"
#define PAD_IZQUIERDA "padIzquierda"
#define CIRCULO "circulo"
#define ARRIBA "arriba"
#define	ABAJO "abajo"
#define	IZQUIERDA "derecha"
#define	DERECHA "izquierda"
#define RESOLUCION_640 640
#define RESOLUCION_640_ALTO 480
#define RESOLUCION_640_ANCHO 640
#define RESOLUCION_800 800
#define RESOLUCION_800_ALTO 600
#define RESOLUCION_800_ANCHO 800
#define RESOLUCION_1024 1024
#define RESOLUCION_1024_ALTO 768
#define RESOLUCION_1024_ANCHO 1024
#define RESOLUCION_1280 1280
#define RESOLUCION_1280_ALTO 768
#define RESOLUCION_1280_ANCHO 1280
#define POS_PAD1_Y_PORCENTAJE  0.88
#define POS_PAD2_Y_PORCENTAJE  0.08
#define RADIO__TEJO "radioTejo"
#define BASE__PAD "basePad"
#define ALTURA__PAD "alturaPad"
#define VELOCIDAD__TEJO  "velocidadTejo"
#define VELOCIDAD__PAD  "velocidadPad"
#define IDTEXTURA__TEJO "idTexturaTejo"
#define IDTEXTURA__PAD "idTexturaPad"
#define BASE_ARCO 10

#define ID "id"
#define RADIO "radio"
#define LADO "lado"
#define BASE "base"
#define TIPO "tipo"
#define ALTURA "altura"
#define VELOCIDAD "velocidad"
#define PATH "path"
#define TEXTURA "textura"
#define CUADRADO "cuadrado"
#define RECTANGULO "rectangulo"
#define TRIANGULO "triangulo"
#define TEJO "tejo"
#define PAD "pad"
#define PAD_CLIENTE1 "PAD1"
#define PAD_CLIENTE2 "PAD2"
#define CIRCULO "circulo"
#define DELIMITADOR "\""
#define GENERAL "General"
#define TEXTURA_FIG "texturaFig"
#define TEXTURA_ESC "texturaEsc"
#define RESOLUCION "resolucion"
#define COLOR_FONDO_FIG "colorFondoFig"
#define COLOR_FONDO_ESC "colorFondoEsc"
#define COLOR_LINEA "colorLinea"
#define POS_X "x"
#define POS_Y "y"
#define POSICION_X 'x'
#define POSICION_Y 'y'
#define POS_X1 "x1"
#define POS_Y1 "y1"
#define POS_X2 "x2"
#define POS_Y2 "y2"
#define POS_X3 "x3"
#define POS_Y3 "y3"
#define SEGMENTO "segmento"
#define COLOR_FIGURA "colorFigura"
#define ID_TEXTURA "idTextura"
#define X1 "x1"
#define X2  "x2"
#define Y1 "y1"
#define Y2 "y2"
#define SINVALOR "sinValor"
#define POS_TEJO_X_INICIAL  150
#define POS_TEJO_Y_INICIAL  300
#define POS_PAD1_X_INICIAL  710
#define POS_PAD1_Y_INICIAL  240
#define POS_PAD2_X_INICIAL  56
#define POS_PAD2_Y_INICIAL  240
#define PORCENTAJE_ARCO 0.4
#define PORCENTAJE_TEJO_PUNTAJES 0.03
#define  PIXELES_SALTO 2
#define  PIXELES_SALTO_TEJO 3
#define  NUM_TECLAS 9
#define MARCADOR_TAG  '-'
#define PUNTAJE_GOL 10
//tamanio de letra de los puntajes
#define TAMANIO_LETRA 60
#define ANCHO_PUNTAJES 100
#define ALTO_PUNTAJES 100
#define PUNTAJE_GANADOR_NIVEL 70
#define BASE_TRIANGULO_DERECHA "DERECHA"
#define BASE_TRIANGULO_IZQUIERDA "IZQUIERDA"
#define BASE_TRIANGULO_ABAJO "ABAJO"
#define BASE_TRIANGULO_ARRIBA "ARRIBA"
#define CANT_NIVELES 3

#define DEC_LONG_PAD 0
#define DEC_LONG_PAD_VS 1
#define DEC_RADIO_TEJO 2
#define INC_LONG_PAD 3
#define INC_LONG_PAD_VS 4
#define INC_RADIO_TEJO 5
#define INC_VELOCIDAD_TEJO 6
#define PEGAMENTO_TEJO 7
#define FRENO_TEJO 8
#endif
